<a href="https://colab.research.google.com/github/Daryna-Ruban/Machine-learning/blob/main/%D0%A0%D1%83%D0%B1%D0%B0%D0%BD_%D0%9B%D0%91_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Лабораторна робота 1
**Завдання 1**
Створіть одновимірний масив (вектор) з числами, які є оберненими значеннями
простих чисел, починаючи з 2, та виведіть його значення

In [1]:
import sympy as sp

# Задаємо кількість простих чисел, які хочемо отримати
num_primes = 10

# Отримуємо перші num_primes простих чисел, починаючи з 2
primes = list(sp.primerange(2, sp.prime(num_primes + 1)))

# Створюємо вектор з обернених значень цих простих чисел
inverse_primes = [1/p for p in primes]

# Виводимо значення вектора
print("Прості числа:", primes)
print("Обернені значення простих чисел:", inverse_primes)

Прості числа: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
Обернені значення простих чисел: [0.5, 0.3333333333333333, 0.2, 0.14285714285714285, 0.09090909090909091, 0.07692307692307693, 0.058823529411764705, 0.05263157894736842, 0.043478260869565216, 0.034482758620689655]


**Завдання 2**
Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
квадратних коренів перших натуральних чисел

In [2]:
import numpy as np

# Створюємо масив з перших 9 натуральних чисел
natural_numbers = np.arange(1, 10)

# Обчислюємо квадратні корені цих чисел
square_roots = np.sqrt(natural_numbers)

# Перетворюємо одновимірний масив у двовимірний масив (матрицю) 3x3
matrix = square_roots.reshape((3, 3))

# Виводимо значення матриці
print("Матриця 3x3 з квадратних коренів перших натуральних чисел:")
print(matrix)

Матриця 3x3 з квадратних коренів перших натуральних чисел:
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


** Завдання 3** Створіть масив розміром 3x3, заповніть його випадковими цілими числами від -10 до 10 та знайдіть суму елементів кожного рядка.


In [3]:
import numpy as np

# Створюємо масив розміром 3x3, заповнений випадковими цілими числами від -10 до 10
matrix = np.random.randint(-10, 11, size=(3, 3))

# Виводимо створену матрицю
print("Матриця 3x3 з випадкових цілих чисел:")
print(matrix)

# Знаходимо суму елементів кожного рядка
row_sums = np.sum(matrix, axis=1)

# Виводимо суму елементів кожного рядка
print("\nСума елементів кожного рядка:")
print(row_sums)

Матриця 3x3 з випадкових цілих чисел:
[[-10   1   6]
 [  2  -9   4]
 [ -3  -4   4]]

Сума елементів кожного рядка:
[-3 -3 -3]


**Завдання 4** Створіть масив розміром 4x4, заповніть його випадковими дійсними числами від -1.0 до 1.0 та виведіть його значення

In [4]:
import numpy as np

# Створюємо масив розміром 4x4, заповнений випадковими дійсними числами від -1.0 до 1.0
matrix = np.random.uniform(-1.0, 1.0, size=(4, 4))

# Виводимо створену матрицю
print("Матриця 4x4 з випадкових дійсних чисел:")
print(matrix)


Матриця 4x4 з випадкових дійсних чисел:
[[-0.55084878  0.34653757 -0.44030699 -0.85346798]
 [-0.09509673  0.5386734   0.10251219 -0.36369578]
 [-0.14829705 -0.53786481  0.38342531  0.89973068]
 [-0.1241553   0.63156357 -0.56946513 -0.48867388]]


**Завдання 5** Створіть два одновимірних масиви розміром 8, заповніть їх випадковими цілими числами в діапазоні від 5 до 10 та виконайте на них поелементні операції додавання, віднімання та множення

In [6]:
import numpy as np

# Створюємо два одновимірних масиви розміром 8, заповнених випадковими цілими числами від 5 до 10
array1 = np.random.randint(5, 11, size=8)
array2 = np.random.randint(5, 11, size=8)

# Виконуємо поелементні операції
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

# Виводимо результати
print("Перший масив:")
print(array1)
print("Другий масив:")
print(array2)
print("\nРезультат поелементного додавання:")
print(addition)
print("\nРезультат поелементного віднімання:")
print(subtraction)
print("\nРезультат поелементного множення:")
print(multiplication)

Перший масив:
[ 8  6  9  5  7  9 10 10]
Другий масив:
[10  9  8 10  7  9  9  9]

Результат поелементного додавання:
[18 15 17 15 14 18 19 19]

Результат поелементного віднімання:
[-2 -3  1 -5  0  0  1  1]

Результат поелементного множення:
[80 54 72 50 49 81 90 90]


**Завдання 6** Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 1 до 15 та знайдіть їх добуток

In [7]:
import numpy as np

# Створюємо дві матриці 4x4, заповнені випадковими цілими числами від 1 до 15
matrix1 = np.random.randint(1, 16, size=(4, 4))
matrix2 = np.random.randint(1, 16, size=(4, 4))

# Обчислюємо добуток матриць
matrix_product = np.dot(matrix1, matrix2)

# Виводимо результати
print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)
print("\nДобуток матриць:")
print(matrix_product)


Перша матриця:
[[ 9  2  3 14]
 [ 5  2  9 12]
 [ 8  9  5 12]
 [ 7 13  8  2]]

Друга матриця:
[[ 3  9  2 15]
 [ 2  6  9  5]
 [ 2  6 14  9]
 [ 7 10  6  5]]

Добуток матриць:
[[135 251 162 242]
 [121 231 226 226]
 [136 276 239 270]
 [ 77 209 255 252]]


**Завдання 7** Створіть дві матриці розміром 4x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 6 та перемножте їх між собою.


In [8]:
import numpy as np

# Створюємо випадкові матриці
matrix1 = np.random.randint(1, 7, size=(4, 2))
matrix2 = np.random.randint(1, 7, size=(2, 2))

print("Матриця 4x2:")
print(matrix1)

print("\nМатриця 2x2:")
print(matrix2)

# Перемножуємо матриці
result = np.dot(matrix1, matrix2)

print("\nРезультат перемноження:")
print(result)

Матриця 4x2:
[[4 6]
 [2 2]
 [4 6]
 [6 5]]

Матриця 2x2:
[[5 1]
 [6 4]]

Результат перемноження:
[[56 28]
 [22 10]
 [56 28]
 [60 26]]


**Завдання 8** Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [9]:
import numpy as np

# Створюємо випадкову матрицю розміром 3x3
matrix = np.random.randint(1, 11, size=(3, 3))

print("Оригінальна матриця:")
print(matrix)

# Перевіряємо, чи матриця є невиродженою (має обернену матрицю)
if np.linalg.det(matrix) == 0:
    print("\nМатриця є виродженою і не має оберненої матриці.")
else:
    # Знаходимо обернену матрицю
    inverse_matrix = np.linalg.inv(matrix)
    print("\nОбернена матриця:")
    print(inverse_matrix)

Оригінальна матриця:
[[2 4 1]
 [6 3 5]
 [1 1 3]]

Обернена матриця:
[[-0.09756098  0.26829268 -0.41463415]
 [ 0.31707317 -0.12195122  0.09756098]
 [-0.07317073 -0.04878049  0.43902439]]


**Завдання 9** Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 100 та транспонуйте її.

In [10]:
import numpy as np

# Створюємо випадкову матрицю розміром 4x4
matrix = np.random.uniform(0, 100, size=(4, 4))

print("Оригінальна матриця:")
print(matrix)

# Транспонуємо матрицю
transposed_matrix = np.transpose(matrix)

print("\nТранспонована матриця:")
print(transposed_matrix)

Оригінальна матриця:
[[62.64166602 13.04328601 12.76972312 56.71851798]
 [52.29763072 39.52789466  4.51683126 67.30187385]
 [47.17385185 25.83773585 46.37302515  9.21216958]
 [ 6.57775233 94.25184722 85.57059645 69.3260778 ]]

Транспонована матриця:
[[62.64166602 52.29763072 47.17385185  6.57775233]
 [13.04328601 39.52789466 25.83773585 94.25184722]
 [12.76972312  4.51683126 46.37302515 85.57059645]
 [56.71851798 67.30187385  9.21216958 69.3260778 ]]


**Завдання 10** Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [12]:
import numpy as np

# Створюємо матрицю розміром 3x4 з випадковими дійсними числами від 0 до 1
matrix = np.random.uniform(0, 1, size=(3, 4))

# Створюємо вектор розміром 4x1 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=(4, 1))

print("Матриця (3x4):")
print(matrix)

print("\nВектор (4x1):")
print(vector)

# Знаходимо добуток матриці на вектор
result = np.dot(matrix, vector)

print("\nРезультат добутку матриці на вектор:")
print(result)

Матриця (3x4):
[[0.96957595 0.45419669 0.58839586 0.99776242]
 [0.69671871 0.66380741 0.18337005 0.00423559]
 [0.93138897 0.70379844 0.84735979 0.59048428]]

Вектор (4x1):
[[4]
 [8]
 [1]
 [9]]

Результат добутку матриці на вектор:
[[17.08013493]
 [ 8.31882452]
 [15.51766177]]


**Висновок:** я згадала, як створювати різні типи матриць і векторів, заповнених випадковими числами, і виконула базові операції з ними, такі як множення матриць, транспонування та обчислення оберненої матриці, множення на верктор
